name: Submit New Prompt
description: Submit a new prompt to the library
title: "[New Prompt]: "
labels: ["prompt-submission"]
body:
  - type: input
    id: title
    attributes:
      label: Prompt Title
      description: The title of the prompt.
      placeholder: e.g., React Component Generator
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of what this prompt does.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - coding
        - productivity
        - writing
        - other
    validations:
      required: true

  - type: input
    id: subcategory
    attributes:
      label: Subcategory (Optional)
      description: e.g., react, email, debugging. If left empty, it will be placed in the root of the category.
      placeholder: react
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated list of tags.
      placeholder: react, javascript, component
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: Prompt Content
      description: The actual prompt content in Markdown.
    validations:
      required: true
